In [1]:
# Q3: Scaled Dot-Product Attention
import numpy as np

def scaled_dot_product_attention(Q, K, V):
    d_k = Q.shape[-1]
    scores = np.dot(Q, K.T) / np.sqrt(d_k)
    weights = np.exp(scores) / np.sum(np.exp(scores), axis=1, keepdims=True)
    output = np.dot(weights, V)
    print("Attention Weights:\n", weights)
    print("Output:\n", output)

Q = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
K = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
V = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
scaled_dot_product_attention(Q, K, V)

# --- Short Answer ---
print("\nQ3 Short Answers:")
print("1. Why divide by sqrt(d):")
print("   - To avoid large dot products that cause vanishing gradients in softmax.")

print("2. Benefit of self-attention:")
print("   - Helps relate all words in a sentence to each other for better context.")

Attention Weights:
 [[0.73105858 0.26894142]
 [0.26894142 0.73105858]]
Output:
 [[2.07576569 3.07576569 4.07576569 5.07576569]
 [3.92423431 4.92423431 5.92423431 6.92423431]]

Q3 Short Answers:
1. Why divide by sqrt(d):
   - To avoid large dot products that cause vanishing gradients in softmax.
2. Benefit of self-attention:
   - Helps relate all words in a sentence to each other for better context.
